/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementsystem;
import com.mysql.cj.xdevapi.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class NEW_PATIENT extends javax.swing.JFrame {

    /**
     * Creates new form NEW_PATIENT
     */
    public NEW_PATIENT() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        r2 = new javax.swing.JCheckBox();
        r1 = new javax.swing.JCheckBox();
        number = new javax.swing.JTextField();
        disease = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        deposit = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        roomComboBox = new javax.swing.JComboBox<>();

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Room");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(0, 102, 102));
        jPanel32.setForeground(new java.awt.Color(255, 255, 255));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Gender:");
        jPanel32.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 60, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel32.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, 20));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Room:");
        jPanel32.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 50, -1));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("Deposit:");
        jPanel32.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, -1));

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Number:");
        jPanel32.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 60, -1));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Disease:");
        jPanel32.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Name:");
        jPanel32.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 50, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID:");
        jPanel32.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 30, -1));

        r2.setBackground(new java.awt.Color(0, 102, 102));
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("Female");
        jPanel32.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        r1.setBackground(new java.awt.Color(0, 102, 102));
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("Male");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel32.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));
        jPanel32.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 130, 20));
        jPanel32.add(disease, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 130, 20));

        date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("jLabel1");
        jPanel32.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 130, -1));
        // Assuming jLabel is your JLabel instance
        date.setText(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        jPanel32.add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 130, 20));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Time:");
        jPanel32.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 50, -1));

        b1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 102, 102));
        b1.setText("Add");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel32.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel32.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD PATIENT");
        jPanel32.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        combobox.setForeground(new java.awt.Color(51, 51, 51));
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNIC", "Driving License", " ", " " }));
        combobox.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.black));
        jPanel32.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, 20));

        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "101", "102", "103", "200", "201", "202", "203", "300", "301", "302", "303", "304" }));
        roomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomComboBoxActionPerformed(evt);
            }
        });
        jPanel32.add(roomComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 130, -1));
        try {
            // Step 1: Establish Database Connection
            java.sql.Connection con = DatabaseConnection.getInstance().getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed!");
                return;
            }

            // Step 2: Clear and Populate ComboBox
            roomComboBox.removeAllItems();
            //        roomComboBox.addItem("Select a Room"); // Placeholder option

            // Step 3: Fetch Room Numbers
            java.sql.ResultSet rs = con.createStatement().executeQuery("SELECT room_no FROM Room");
            while (rs.next()) {
                roomComboBox.addItem(rs.getString("room_no"));
            }

            // Repaint ComboBox UI to reflect changes
            roomComboBox.repaint();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

        getContentPane().add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
 if (evt.getSource() == b1) {
        try {
            // Step 1: Establish Database Connection
            java.sql.Connection con = DatabaseConnection.getInstance().getConnection();
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Database connection failed!");
                return;
            }
boolean status;
            // Step 2: Retrieve Input Values from the Form
            String radioBTN = null;
            if (r1.isSelected()) {
                radioBTN = "Male";
            } else if (r2.isSelected()) {
                radioBTN = "Female";
            }

            String s1 = (String) combobox.getSelectedItem();  // ID
            String s2 = number.getText();                    // Phone Number
            String s3 = name.getText();                      // Name
            String s4 = radioBTN;                            // Gender
            String s5 = disease.getText();                   // Disease
            String s6 = (String) roomComboBox.getSelectedItem(); // Room
            String s7 = date.getText();                      // Date
            String s8 = deposit.getText();                   // Deposit

            // Step 3: Validate Inputs (Optional, but recommended)
            if (s1 == null || s1.isEmpty() || s3.isEmpty() || s5.isEmpty() || s6 == null || s6.isEmpty() || s7.isEmpty() || s8.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all required fields!");
                return;
            }

            // Step 4: Prepare SQL Query using PreparedStatement
           String query = "INSERT INTO patient_info (ID, Number, Name, Gender, Patient_Disease, Room_Number, Time, Deposite) "
                         + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setString(1, s1); // ID
            pstmt.setString(2, s2); // Number
            pstmt.setString(3, s3); // Name
            pstmt.setString(4, s4); // Gender
            pstmt.setString(5, s5); // Disease
            pstmt.setString(6, s6); // Room
            pstmt.setString(7, s7); // Date
            pstmt.setString(8, s8); // Deposit

            // Step 5: Execute Query
            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Patient information added successfully!");
               status=true;
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add patient information!");
            }

            // Step 6: Close resources
            

        } catch (SQLException ex) {
            // Log and show error to user
            Logger.getLogger(NEW_PATIENT.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
         Admin a=new Admin();
      a.setVisible(true);
      a.pack();
      a.setLocationRelativeTo(null);
        this.dispose();
    }
    }//GEN-LAST:event_b1ActionPerformed

    private void roomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomComboBoxActionPerformed
 
    }//GEN-LAST:event_roomComboBoxActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Admin a=new Admin();
      a.setVisible(true);
      a.pack();
      a.setLocationRelativeTo(null);
     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        NEW_PATIENT p=new NEW_PATIENT();
 
        java.sql.Connection con = DatabaseConnection.getInstance().getConnection();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEW_PATIENT().setVisible(true);
               p.pack();
               p.setLocationRelativeTo(null);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel date;
    private javax.swing.JTextField deposit;
    private javax.swing.JTextField disease;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JCheckBox r1;
    private javax.swing.JCheckBox r2;
    private javax.swing.JComboBox<String> roomComboBox;
    // End of variables declaration//GEN-END:variables
}
